### ISSUE TITLE
Get Rid of DRM

### ISSUE THREAD

**Issue by KaspianDev** [funkemunky/Kauri#16]
I am thankful for open sourcing it even, however open source and DRM don't really stick together + it doesn't make sense in that state. Consider removing it.

**Comment by Izibane** [comment]
I am thankful for your issue even, however ratio + no one cares. Consider deleting this.

**Comment by KaspianDev** [comment]
> I am thankful for your issue even, however ratio + no one cares. Consider deleting this.

Grow up

**Comment by funkemunky** [comment]
Removed DRM: https://github.com/funkemunky/Kauri/pull/17
