### ISSUE TITLE
Many ice falses with Speed(E) works better if u use trapdoors but sometimes without.

### ISSUE THREAD

**Issue by FooFieOwO** [funkemunky/Kauri#31]
Tested with 1.18
https://www.youtube.com/watch?v=V9wR27UX_gs

**Comment by FooFieOwO** [comment]
It works if ur standing still for around 10 secs and then start sprint jump

**Comment by Chanakan55991** [comment]
![image](https://user-images.githubusercontent.com/80865605/169513156-04c2c0b4-8124-4c8c-81e9-f4567e514346.png)
it also happens very frequently for me even without a trapdoor

**Comment by funkemunky** [comment]
Fixed in fd66ba6ee7f9e01b314abf6df1de0f6132cf6284
