### ISSUE TITLE
Possibly incompatible license

### ISSUE THREAD

**Issue by KaspianDev** [funkemunky/Kauri#63]
Hi, thanks for all your work in OSS. However from my research looks like AGPL might be incompatible with GPL. I couldn't find official source saying so thought.

**Comment by MWHunter** [comment]
AGPL can use GPL, GPL cannot use AGPL.

**Comment by KaspianDev** [comment]
> AGPL can use GPL, GPL cannot use AGPL. LGPL cannot use GPL. GPL can use LGPL.
> 
> LGPL -> GPL -> AGPL
> 
> LGPL: API usage isn't a combined work GPL: API usage is a combined work AGPL: API usage is a combined work, usage over web is considered distribution so therefore players may request sources.
> 
> You can license forwards but not backwards, as progressively the license becomes more strict.

so it is compatible?
