### ISSUE TITLE
can't load cc.funkemunky.api.utils.MiscUtils

### ISSUE THREAD

**Issue by nuym** [funkemunky/Kauri#65]
![image](https://user-images.githubusercontent.com/102905510/190879752-42fcdb93-c930-4aef-aa9d-797f99e13305.png)
![image](https://user-images.githubusercontent.com/102905510/190879764-1b4c8541-cbe7-47ca-8882-0680b21cfc42.png)
![image](https://user-images.githubusercontent.com/102905510/190879770-24280987-9d47-4ab1-b6b6-1f006d872d0c.png)

**Comment by funkemunky** [comment]
Are you running Spigot or CraftBukkit?
