### ISSUE TITLE
[Feature Request] Command to view allowlist entries

### ISSUE THREAD

**Issue by lrmtheboss** [funkemunky/Kauri#73]
Add a command like `/antivpn allowlist show <page>` to allow users with permission to view all entries in the allow list. Maybe use a page format of X entries per page

**Comment by mgmadnesstv** [comment]
You opened the issue for the AntiCheat did you mean to open it for the AntiVPN? if so open a issue here
https://github.com/funkemunky/AntiVPN/issues/new/choose
